import emailjs from '@emailjs/browser';
import { supabase } from '@/integrations/supabase/client';

// Initialize EmailJS
const EMAILJS_SERVICE_ID = import.meta.env.VITE_EMAILJS_SERVICE_ID;
const EMAILJS_PUBLIC_KEY = import.meta.env.VITE_EMAILJS_PUBLIC_KEY;

// Template IDs for different email types
const TEMPLATES = {
  INVOICE: import.meta.env.VITE_EMAILJS_INVOICE_TEMPLATE_ID,
  PAYMENT_REMINDER: import.meta.env.VITE_EMAILJS_PAYMENT_REMINDER_TEMPLATE_ID,
  PAYMENT_RECEIVED: import.meta.env.VITE_EMAILJS_PAYMENT_RECEIVED_TEMPLATE_ID,
  QUOTE: import.meta.env.VITE_EMAILJS_QUOTE_TEMPLATE_ID
};

// Initialize EmailJS
if (emailjs && EMAILJS_PUBLIC_KEY) {
  emailjs.init(EMAILJS_PUBLIC_KEY);
}

/**
 * Get user's business settings for email branding
 */
const getUserBusinessSettings = async (userId) => {
  try {
    const { data, error } = await supabase
      .from('business_settings')
      .select('*')
      .eq('user_id', userId)
      .single();

    if (error) {
      console.error('Error fetching business settings:', error);
      // Return default settings if user hasn't set up their business info yet
      return {
        company_name: 'My Business',
        company_email: null,
        company_phone: null,
        company_website: null,
        address_line1: null,
        city: null,
        state: null,
        country: 'India',
        logo_url: null,
        primary_color: '#6366f1',
        email_signature: null,
        email_footer: null
      };
    }

    return data;
  } catch (error) {
    console.error('Error in getUserBusinessSettings:', error);
    return null;
  }
};

/**
 * Send invoice email with user's branding
 */
export const sendInvoiceEmail = async (invoiceData, clientEmail, userId) => {
  try {
    console.log('=== SENDING INVOICE EMAIL ===');
    
    // Get user's business settings
    const businessSettings = await getUserBusinessSettings(userId);
    if (!businessSettings) {
      throw new Error('Could not fetch business settings');
    }

    // Prepare email template parameters with user's branding
    const templateParams = {
      // Recipient
      to_email: clientEmail,
      to_name: invoiceData.clientName,
      
      // Invoice Details
      invoice_number: invoiceData.invoiceNumber,
      invoice_date: invoiceData.date,
      due_date: invoiceData.dueDate,
      total_amount: invoiceData.totalAmount,
      currency: businessSettings.currency || 'INR',
      
      // User's Business Information (Dynamic Branding)
      company_name: businessSettings.company_name,
      company_email: businessSettings.company_email,
      company_phone: businessSettings.company_phone,
      company_website: businessSettings.company_website,
      company_address: [
        businessSettings.address_line1,
        businessSettings.address_line2,
        businessSettings.city,
        businessSettings.state,
        businessSettings.country
      ].filter(Boolean).join(', '),
      
      // Branding
      logo_url: businessSettings.logo_url,
      primary_color: businessSettings.primary_color,
      
      // Email Content
      email_signature: businessSettings.email_signature || `Best regards,\n${businessSettings.company_name}`,
      email_footer: businessSettings.email_footer || `This invoice was generated by ${businessSettings.company_name}`,
      
      // Invoice Items (if needed)
      invoice_items: invoiceData.items ? JSON.stringify(invoiceData.items) : '',
      
      // Payment Information
      bank_name: businessSettings.bank_name,
      account_number: businessSettings.account_number,
      ifsc_code: businessSettings.ifsc_code,
      upi_id: businessSettings.upi_id,
      
      // Additional
      notes: invoiceData.notes || '',
      terms: invoiceData.terms || 'Payment due within 30 days',
      
      // System
      current_year: new Date().getFullYear()
    };

    console.log('Sending invoice email with user branding:', {
      companyName: businessSettings.company_name,
      companyEmail: businessSettings.company_email,
      clientEmail: clientEmail
    });

    const result = await emailjs.send(
      EMAILJS_SERVICE_ID,
      TEMPLATES.INVOICE,
      templateParams
    );

    console.log('Invoice email sent successfully:', result);
    return { success: true, result };

  } catch (error) {
    console.error('Error sending invoice email:', error);
    return { success: false, error: error.message };
  }
};

/**
 * Send payment reminder with user's branding
 */
export const sendPaymentReminderEmail = async (invoiceData, clientEmail, userId, reminderType = 'gentle') => {
  try {
    const businessSettings = await getUserBusinessSettings(userId);
    if (!businessSettings) {
      throw new Error('Could not fetch business settings');
    }

    const templateParams = {
      to_email: clientEmail,
      to_name: invoiceData.clientName,
      
      invoice_number: invoiceData.invoiceNumber,
      original_due_date: invoiceData.dueDate,
      days_overdue: invoiceData.daysOverdue || 0,
      total_amount: invoiceData.totalAmount,
      currency: businessSettings.currency || 'INR',
      
      // User's branding
      company_name: businessSettings.company_name,
      company_email: businessSettings.company_email,
      company_phone: businessSettings.company_phone,
      
      reminder_type: reminderType, // gentle, firm, final
      
      email_signature: businessSettings.email_signature || `Best regards,\n${businessSettings.company_name}`,
      current_year: new Date().getFullYear()
    };

    const result = await emailjs.send(
      EMAILJS_SERVICE_ID,
      TEMPLATES.PAYMENT_REMINDER,
      templateParams
    );

    return { success: true, result };
  } catch (error) {
    console.error('Error sending payment reminder:', error);
    return { success: false, error: error.message };
  }
};

/**
 * Send payment received confirmation with user's branding
 */
export const sendPaymentReceivedEmail = async (paymentData, clientEmail, userId) => {
  try {
    const businessSettings = await getUserBusinessSettings(userId);
    if (!businessSettings) {
      throw new Error('Could not fetch business settings');
    }

    const templateParams = {
      to_email: clientEmail,
      to_name: paymentData.clientName,
      
      invoice_number: paymentData.invoiceNumber,
      payment_amount: paymentData.amount,
      payment_date: paymentData.date,
      payment_method: paymentData.method || 'Bank Transfer',
      currency: businessSettings.currency || 'INR',
      
      // User's branding
      company_name: businessSettings.company_name,
      company_email: businessSettings.company_email,
      
      email_signature: businessSettings.email_signature || `Thank you for your business!\n${businessSettings.company_name}`,
      current_year: new Date().getFullYear()
    };

    const result = await emailjs.send(
      EMAILJS_SERVICE_ID,
      TEMPLATES.PAYMENT_RECEIVED,
      templateParams
    );

    return { success: true, result };
  } catch (error) {
    console.error('Error sending payment confirmation:', error);
    return { success: false, error: error.message };
  }
};

/**
 * Send quote/estimate with user's branding
 */
export const sendQuoteEmail = async (quoteData, clientEmail, userId) => {
  try {
    const businessSettings = await getUserBusinessSettings(userId);
    if (!businessSettings) {
      throw new Error('Could not fetch business settings');
    }

    const templateParams = {
      to_email: clientEmail,
      to_name: quoteData.clientName,
      
      quote_number: quoteData.quoteNumber,
      quote_date: quoteData.date,
      valid_until: quoteData.validUntil,
      total_amount: quoteData.totalAmount,
      currency: businessSettings.currency || 'INR',
      
      // User's branding
      company_name: businessSettings.company_name,
      company_email: businessSettings.company_email,
      company_phone: businessSettings.company_phone,
      company_website: businessSettings.company_website,
      
      quote_items: quoteData.items ? JSON.stringify(quoteData.items) : '',
      notes: quoteData.notes || '',
      
      email_signature: businessSettings.email_signature || `Best regards,\n${businessSettings.company_name}`,
      current_year: new Date().getFullYear()
    };

    const result = await emailjs.send(
      EMAILJS_SERVICE_ID,
      TEMPLATES.QUOTE,
      templateParams
    );

    return { success: true, result };
  } catch (error) {
    console.error('Error sending quote email:', error);
    return { success: false, error: error.message };
  }
};

/**
 * Utility function to validate email configuration
 */
export const validateEmailConfig = () => {
  const isConfigured = EMAILJS_SERVICE_ID && EMAILJS_PUBLIC_KEY && 
    EMAILJS_SERVICE_ID !== 'your_service_id_here' && 
    EMAILJS_PUBLIC_KEY !== 'your_public_key_here';
    
  return {
    isConfigured,
    serviceId: EMAILJS_SERVICE_ID ? 'Set' : 'Missing',
    publicKey: EMAILJS_PUBLIC_KEY ? 'Set' : 'Missing',
    templates: {
      invoice: TEMPLATES.INVOICE ? 'Set' : 'Missing',
      paymentReminder: TEMPLATES.PAYMENT_REMINDER ? 'Set' : 'Missing',
      paymentReceived: TEMPLATES.PAYMENT_RECEIVED ? 'Set' : 'Missing',
      quote: TEMPLATES.QUOTE ? 'Set' : 'Missing'
    }
  };
};