// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Debug logging (will be visible in browser console)
console.log('Supabase Config:', {
  url: SUPABASE_URL ? 'SET' : 'NOT SET',
  key: SUPABASE_PUBLISHABLE_KEY ? 'SET' : 'NOT SET',
  urlValue: SUPABASE_URL?.substring(0, 30) + '...' // Show first 30 chars
});

// Fallback to prevent crash if keys are missing in development
const finalUrl = SUPABASE_URL || 'https://placeholder.supabase.co';
const finalKey = SUPABASE_PUBLISHABLE_KEY || 'placeholder-key';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn("⚠️ Supabase credentials are missing. Authentication will not work.");
  console.warn("Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(finalUrl, finalKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'x-client-info': 'supabase-js-web'
    }
  }
});